### ISSUE TITLE
Raycaster not intersecting with last line segment

### ISSUE THREAD

**Issue by OlivierKamers** [ryanking1809/three-line-raycast#1]
Hi!

We've been trying out this raycast implementation and found an issue where the raycast function doesn't intersect with the last segment of a line or polygon. When changing `l = startPoints.count - 1` to `l = startPoints.count` [here](https://github.com/ryanking1809/three-line-raycast/blob/master/src/index.js#L26), the problem is fixed.
What is the reason for not looping over all points and does the fix make sense? 
We're using threejs version 0.107.0.

Thanks!

**Comment by ryanking1809** [comment]
Sorry, that was an artefact from the meshline algorithm I adapted. Fixed in `three-line-raycast@1.0.2` - thanks for picking it up!
